local ItemData = {

	Branch = {
		Name = "Branch",
		Description = "A simple branch, not very effective.",
		ItemType = "Weapon",
		Image = "rbxassetid://17753344129", -- Replace with actual asset ID
		Uses = 2,
		Enabled = true,
	},
	Sword = {
		Name = "Sword",
		Description = "A sharp sword, effective in combat.",
		ItemType = "Weapon",
		Image = "rbxassetid://17753344129", -- Replace with actual asset ID
		Uses = 5,
		Enabled = true,
	},
	Shield = {
		Name = "Shield",
		Description = "A sturdy shield, provides protection.",
		ItemType = "Weapon",
		Image = "rbxassetid://17753344129", -- Replace with actual asset ID
		Uses = 1,
		Enabled = true,
	},
}

return ItemData
