local ItemData = {

	Branch = {
		Name = "Branch",
		Description = "A simple branch, not very effective.",
		ItemType = "Weapon",
		Color = Color3.fromRGB(139, 69, 19),
		Image = "rbxassetid://5684867096", -- Replace with actual asset ID
		Uses = 2,
		Enabled = true,
	},
	Sword = {
		Name = "Sword",
		Description = "A sharp sword, effective in combat.",
		ItemType = "Weapon",
		Color = Color3.fromRGB(18, 106, 154),
		Image = "rbxassetid://17753344155", -- Replace with actual asset ID
		Uses = 5,
		Enabled = true,
	},
	Shield = {
		Name = "Shield",
		Description = "A sturdy shield, provides protection.",
		ItemType = "Weapon",
		Color = Color3.fromRGB(200, 63, 28),
		Image = "rbxassetid://5183840367", -- Replace with actual asset ID
		Uses = 1,
		Enabled = true,
	},
}

return ItemData
