local Weapons = {
	TreeBranch = {
		Name = "Tree Branch",
		ModelName = "TreeBranchModel",
		Description = "A simple branch from a tree.",
		Damage = 5,
		Range = 3,
		AttackAnimation = "rbxassetid://129151358971827",
		Enabled = true,
		Image = "rbxassetid://1091279834",
		ItemType = "Weapon",
	},
	PickAxe = {
		Name = "Pick Axe",
		ModelName = "PickAxeModel",
		Description = "A sturdy sword made of iron.",
		Damage = 15,
		Range = 4,
		AttackAnimation = "rbxassetid://129151358971827",
		Enabled = true,
		Image = "rbxassetid://17753344129",
		ItemType = "Weapon",
	},
}
return Weapons
